apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: composetest-web:latest # Ensure this matches your local image
          imagePullPolicy: Never # Add this line

          ports:
            - containerPort: 5000
